[package]
name = "hearts"
version = "0.0.1"
authors = [ "Derek Williams <derek.williams1@rbs.com>" ]

[dependencies]
hyper = "0.10"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
log = "0.3"
env_logger = "0.3"
clap = "2.11"
